spring.application.name=patient-management
spring.datasource.url=jdbc:postgresql://localhost:5432/patientmanagement
spring.datasource.username=postgres
spring.datasource.password=Thammana@1005
spring.jpa.hibernate.ddl-auto=update
jwt.secret=your_super_secret_and_very_long_signing_key_here